--Users table

CREATE TABLE IF NOT EXISTS Users_Info (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    First_Name VARCHAR(100) NOT NULL,
    Last_Name VARCHAR(100) NOT NULL,
    User_name VARCHAR(100) NOT NULL UNIQUE,
    Email_Id VARCHAR(100) NOT NULL UNIQUE,
    Pass VARCHAR(100) NOT NULL,
)